### PR TITLE
3.10 update

### PR DESCRIPTION
**Pull request by damonkman**
Made changes to allow for specific aura effect due to the new Cluster Jewels giving 30% effect to specific auras. Also updated Guardian and Necro with 3.10 patch notes.

### CODE REVIEW

**Comment by damonkman** [comment]
Looks like there's some issues right now. Also plan to add increased buff effect scaling. Will update that in a bit.

**Comment by shadowmoose** [comment]
Looks good. Thanks for the update - I'd totally missed that this league rolled out aura changes.

Are there further changes you'd like to make before merging? I'll hold off until you can wrap up whatever else you were looking to do.

**Comment by damonkman** [comment]
Okay, that's all I will probably work on for now. The buff effect on you shouldn't apply to auras like Pride, Skitterbots or Banners but I can manually work around that for now. Feel free to Merge now.

**Comment by shadowmoose** [comment]
Looks great! Thanks again for the contribution.

**Pull request merged**
